# Node.js with rollup
# Build a Node.js project using the rollup CLI.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.14.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'ci'
    customEndpoint: "GitHubPackages"
  displayName: 'NPM Install'

- script: npx @vscode/vsce package --no-yarn
  displayName: 'VSCE package'
