blank_issues_enabled: true
contact_links:
  - name: Connection Issues
    url: http://pico-go.net/docs/help/connect/
    about: Struggling to connect? Try this guidance before opening a bug.
  - name: Intellisense, Autocomplete and Linting Issues
    url: https://github.com/cpwood/Pico-Stub/issues
    about: These belong in the Pico-Stub project rather than Pico-Go.