blank_issues_enabled: true
contact_links:
  - name: Breaking Changes
    url: http://pico-go.net/docs/help/breaking-changes/
    about: Functionality that has changed significantly between versions of Pico-Go.
  - name: Connection Issues
    url: http://pico-go.net/docs/help/connect/
    about: Struggling to connect? Try this guidance before opening a bug.
  - name: Intellisense, Auto-complete and Linting Issues
    url: https://github.com/paulober/Pico-W-Stub/issues
    about: These belong in the Pico-W-Stub project rather than Pico-W-Go.