blank_issues_enabled: false
contact_links:
  - name: Breaking changes and known issues [please check before opening an issue!!]
    url: https://github.com/paulober/MicroPico/blob/main/CHANGELOG.md
    about: Functionality that has changed significantly between versions of MicroPico or known issues.
  - name: Intellisense, auto-complete and linting issues
    url: https://github.com/paulober/Pico-W-Stub/issues
    about: These belong in the Pico-W-Stub project rather than MicroPico.
