name: Build MicroPico extension

on:
  pull_request: ~
  push:
    branches-ignore:
      - "dependabot/**"
    paths-ignore:
      - ".idea/**"
      - ".vscode/**"
      - "scripts/**"
      - "**/*.md"
      - ".prettierrc.json"
      - "LICENSE"
      - ".editorconfig"
      - ".eslintrc.json"

permissions:
  contents: read
  packages: read

jobs:
  build:
    name: "Build ubuntu-latest"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node v20.14.0
        uses: actions/setup-node@v4
        with:
          node-version: "20.14.0"
          registry-url: "https://npm.pkg.github.com"
          scope: "@paulober"
          token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'npm'

      - name: Setup Python v3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install NPM Dependencies And Download Stubs
        shell: bash
        run: |
          sed -i '1i//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}' .npmrc
          npm ci --no-audit
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Package Extension
        run: npx @vscode/vsce package --no-yarn -o micropico-${{ github.sha }}.vsix

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: micropico-${{ github.sha }}.vsix
          path: micropico-${{ github.sha }}.vsix
