name: Build Pico-W-Go

on:
  pull_request: ~
  push:
    branches-ignore:
      - "dependabot/**"
    paths-ignore:
      - "doc/**"

jobs:
  build:
    name: "Build ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16.14"

      - name: Install Dependencies
        shell: bash
        run: |
          npm install -g pnpm
          pnpm install npx
          pnpm install --no-audit

      - name: Package Extension
        run: npx vsce package -o picowgo-${{ github.sha }}.vsix

      - name: Upload VSIX
        #if: github.event_name == 'schedule'
        uses: actions/upload-artifact@v3
        with:
          name: picowgo-nightly.vsix
          path: ./picowgo-${{ github.sha }}.vsix

#   deploy:
#    name: Publish
#    needs: build
#    # if current branch name contains release and is not a PR
#    if: contains(github.ref, 'release') && github.event_name == 'push'
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#
#      - name: Install Production Dependencies
#        run: |
#          npm ci
#          npm prune --production
#
#      - name: Package Extension
#        run: npx vsce package
#
#      - name: Publish Extension
#        run: npx vsce publish --pat ${{ secrets.VSCE_TOKEN }}
