name: Build Pico-W-Go

on:
  pull_request: ~
  push:
    branches-ignore:
      - "dependabot/**"
    paths-ignore:
      - "doc/**"

jobs:
  build:
    name: "Build ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16.14.x"
          registry-url: "https://npm.pkg.github.com"

      - name: Install Dependencies
        shell: bash
        run: npm ci --no-audit

      - name: Package Extension
        run: npx vsce package --no-yarn --dependencies -o picowgo-${{ github.sha }}.vsix

# Stop uploading artifacts for the basic build process
#      - name: Upload VSIX
#        #if: github.event_name == 'schedule'
#        uses: actions/upload-artifact@v3
#        with:
#          name: picowgo-nightly.vsix
#          path: ./picowgo-${{ github.sha }}.vsix
