name: Build Pico-W-Go

on:
  pull_request: ~
  push:
    branches-ignore:
      - "dependabot/**"
    paths-ignore:
      - ".idea/**"
      - ".vscode/**"
      - "**/*.md"
      - ".prettierrc.json"
      - "LICENSE"
      - ".editorconfig"
      - ".eslintrc.json"

permissions:
  contents: read
  packages: read

jobs:
  build:
    name: "Build ubuntu-latest"
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16.14.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@paulober"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Dependencies
        shell: bash
        run: |
          sed -i '1i//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}' .npmrc
          npm ci --no-audit
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Package Extension
        run: npx @vscode/vsce package --no-yarn -o picowgo-${{ github.sha }}.vsix
