name: publish

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - run: npm install
        name: NPM install

      - name: Package
        run: npx vsce package --no-yarn --dependencies

      - run: npx vsce publish --no-yarn --dependencies --target win32-x64 linux-x64 linux-arm64 darwin-x64 darwin-arm64
        name: Publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Visual Studio Code extension package
          path: pico-w-go-*.vsix

      - name: Add artifact to release
        #gh api --method POST -H "Accept: application/vnd.github+json" /repos/paulober/Pico-W-Go/releases/$RELEASE_ID/assets 
        run: gh release upload $RELEASE_TAG_NAME pico-w-go-*.vsix
        env:
          #RELEASE_ID: ${{ github.event.release.id }}
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
